name: Release

on:
  push:
    paths:
      - 'include/version.mk'
      - '.github/workflows/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install tmate
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y tmate openssh-client > /tmp/apt-get.log
          # Generate ssh key if needed
          run: [ -e ~/.ssh/id_rsa ] || ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
          tmate show-messages
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      # - name: Build with Gradle
      #   run: ./gradlew clean build
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build SampleApplication
        run: ./gradlew --no-daemon build

      - name: Setup Debug Session
        uses: csexton/debugger-action@master
   
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: upload
          path: upload

